### PR TITLE
fix(Textarea): Fix label not being reactive (#247)

### LINKED ISSUE #247: Textarea Label issue
class active is not applied on label because the labelActive variable is not reactive.
should have :   `$: labelActive = !!placeholder || value;`
instead of :   `let labelActive = !!placeholder || value;`

### PR DESCRIPTION
**Pull request by V-ed**
This also makes the Textarea more in line with the TextField component

I also fixed autogrow not being updated if value is dynamically updated to a big value, see comments

REPL that shows issue(s) : https://svelte.dev/repl/1154fe4b3434494b88c2e1cf35960c76?version=3.38.1

Closes #247

### CODE REVIEW

File: packages/svelte-materialify/src/components/Textarea/Textarea.svelte [hunk 1]
```diff
@@ -30,33 +30,34 @@
...
     value = '';
-    if (!placeholder) labelActive = false;
   }
 
   function onInput() {
-    if (!validateOnBlur) checkRules();
+    if (!validateOnBlur) validate();
     if (autogrow) {
       textarea.style.height = 'auto';
       textarea.style.height = `${textarea.scrollHeight}px`;
```
Comment (V-ed) [inline packages/svelte-materialify/src/components/Textarea/Textarea.svelte:63]: The only thing I'm concerned is that is the value is dynamically changed and gets too big (and `autogrow` is activated), it might not grow automatically

File: packages/svelte-materialify/src/components/Textarea/Textarea.svelte [hunk 2]
```diff
@@ -30,37 +30,39 @@
...
-      textarea.style.height = 'auto';
-      textarea.style.height = `${textarea.scrollHeight}px`;
-    }
+    if (!validateOnBlur) validate();
+  }
+  
+  $: if (autogrow) {
+    textarea.style.height = 'auto';
+    textarea.style.height = `${textarea.scrollHeight}px`;
   }
```
Comment (V-ed) [inline packages/svelte-materialify/src/components/Textarea/Textarea.svelte:66]: I was concerned that is the value is dynamically changed to a big value, that the `autogrow` wouldn't get applied, so I made that one dynamic too ; is this the right approach?

**Comment by V-ed** [comment]
Also, since I was testing with another commit for the changes to the autogrow property, this would require a squash and merge instead of simply merging @Florian-Schoenherr

**Comment by V-ed** [comment]
ah, the vercel is broken right now, let me see what's the error

**Comment by V-ed** [comment]
Sorry about all the individual commits btw, I really should get a dev build eventually on my local machine, but with svelterial coming up I think I'll wait 😅
